# Generated by Django 4.0.3 on 2022-03-13 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(choices=[('A', 'Hall A'), ('B', 'Hall B'), ('C', 'Hall C')], max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age_rating', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('genre', models.CharField(max_length=200)),
                ('cast', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='images')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthenticationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=2048)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'UserAuthenticationData',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserPersonalData',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('auth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.userauthenticationdata')),
            ],
            options={
                'verbose_name_plural': 'UserPersonalData',
            },
        ),
        migrations.AddField(
            model_name='userauthenticationdata',
            name='user_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.usergroup'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_price', models.CharField(max_length=200)),
                ('invoice_details', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.userpersonaldata')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('mon', 'Monday'), ('tu', 'Tuesday'), ('we', 'Wednesday'), ('th', 'Thursday'), ('fr', 'Friday')], default='No day for this Event was assigned yet', max_length=10)),
                ('time_slot', models.CharField(choices=[('1', '10:00'), ('2', '13:30'), ('3', '17:00'), ('4', '20:30'), ('5', '00:00')], default='No time for this Event was assigned yet', max_length=10)),
                ('type', models.CharField(choices=[('2d', '2D'), ('3d', '3D')], default=('3d', '3D'), max_length=2)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=2048)),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.component')),
            ],
            options={
                'verbose_name_plural': 'ComponentText',
            },
        ),
        migrations.CreateModel(
            name='ComponentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('media_src', models.CharField(max_length=2048)),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.component')),
            ],
            options={
                'verbose_name_plural': 'ComponentMedia',
            },
        ),
    ]
