# Generated by Django 4.0.3 on 2022-03-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='hall_structure',
            field=models.CharField(default='lol', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hall',
            name='hall_name',
            field=models.CharField(choices=[('A', 'Hall A'), ('B', 'Hall B'), ('C', 'Hall C')], max_length=30),
        ),
    ]
