# Generated by Django 4.0.3 on 2022-03-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_hall_hall_structure_alter_hall_hall_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='hall_structure',
            field=models.CharField(editable=False, max_length=10000),
        ),
    ]
