# Generated by Django 4.0.3 on 2022-03-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_hall_hall_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='week_day',
        ),
    ]
