# Generated by Django 4.0.3 on 2022-03-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_remove_event_week_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='week_day',
            field=models.CharField(choices=[('mon', 'Monday'), ('tu', 'Tuesday'), ('we', 'Wednesday'), ('th', 'Thursday'), ('fr', 'Friday')], default='No day for this Event was assigned yet', max_length=10),
        ),
    ]
