# Generated by Django 4.0.3 on 2022-03-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_event_week_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('2d', '2D'), ('3d', '3D')], default=('2d', '2D'), max_length=2),
        ),
    ]
